name: risk_assessment
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.4.3
  - seaborn=0.11.1
  - numpy=1.21.2
  - pandas=1.2.5
  - python=3.9.6
  - scikit-learn=1.0
  - requests
  - flask